version: '3.9'

services:
  mongodb:
    image: 'mongodb/mongodb-community-server:latest'
    environment:
      MONGO_INITDB_DATABASE: kitchensink
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
