name: Build and publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  setup-build-publish:
    if: github.repository == 'yvan-lopez-it/kitchensink-challenge'
    name: Setup, build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Grant execution permissions to the Maven wrapper
      - name: Grant execution permission for Maven wrapper
        run: chmod +x ./mvnw

      # Build Maven package (Skipping Tests as per Dockerfile logic)
      - name: Build with Maven (without tests)
        run: |
          ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip

      # Clean target and re-build for production (Skip Tests)
      - name: Clean and Build Maven package
        run: |
          ./mvnw clean package -DskipTests

      # Docker login to Docker Hub
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      # Docker build the image (Multi-stage)
      - name: Build the Docker image
        run: |
          docker build --build-arg MS_NAME=kitchensink -t kitchensink . -f Dockerfile

      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag kitchensink yvancho/kitchensink:latest

      # Push the image to Docker Hub
      - name: Docker push
        run: docker push yvancho/kitchensink:latest
